# Generated by Django 3.2 on 2024-11-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WarframeName', models.CharField(max_length=25)),
                ('Critical_Utility', models.FloatField()),
                ('CriticalDMG_Utility', models.FloatField()),
                ('Status_Utility', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeaponName', models.CharField(max_length=25)),
                ('WeaponType', models.CharField(max_length=25)),
                ('WeaponSlot', models.CharField(max_length=25)),
                ('Critical_Utility', models.FloatField()),
                ('CriticalDMG_Utility', models.FloatField()),
                ('Status_Utility', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeaponUtility', models.FloatField()),
                ('WeaponName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Utility_WeaponName', to='AppEva3.weapon')),
                ('WeaponSlot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Utility_WeaponSlot', to='AppEva3.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='WarframeUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WarframeUtility', models.FloatField()),
                ('WarframeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Utility_WarframeName', to='AppEva3.warframe')),
            ],
        ),
        migrations.CreateModel(
            name='BuildResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WarframeID', models.IntegerField()),
                ('TotalUtility', models.FloatField()),
                ('Melee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Build_MeleeWeapon', to='AppEva3.weaponutility')),
                ('Primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='Build_PrimaryWeapon', to='AppEva3.weaponutility')),
                ('Secondary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Build_SecondaryWeapon', to='AppEva3.weaponutility')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Build_UserName', to='AppEva3.userdata')),
                ('WarframeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Build_WarframeName', to='AppEva3.warframeutility')),
            ],
        ),
    ]
