# Generated by Django 3.2 on 2024-11-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppEva3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warframeutility',
            name='WarframeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='WarframeID', to='AppEva3.warframe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weaponutility',
            name='WeaponID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='WeaponID', to='AppEva3.weapon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildresume',
            name='Melee',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buildresume',
            name='Primary',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buildresume',
            name='Secondary',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buildresume',
            name='UserName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buildresume',
            name='WarframeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Int_WarframeID', to='AppEva3.warframe'),
        ),
        migrations.AlterField(
            model_name='buildresume',
            name='WarframeName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warframeutility',
            name='WarframeName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='Critical_Utility',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='Status_Utility',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='WeaponName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='WeaponSlot',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='WeaponType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weaponutility',
            name='WeaponName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weaponutility',
            name='WeaponSlot',
            field=models.CharField(max_length=50),
        ),
    ]
