# Generated by Django 3.2 on 2024-11-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEva3', '0002_auto_20241115_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warframeutility',
            name='WarframeID',
        ),
        migrations.RemoveField(
            model_name='weaponutility',
            name='WeaponID',
        ),
    ]
