# Generated by Django 3.2 on 2024-11-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEva3', '0003_auto_20241115_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='TotalUtility',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
