# Generated by Django 3.2 on 2024-11-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEva3', '0004_weapon_totalutility'),
    ]

    operations = [
        migrations.AddField(
            model_name='warframe',
            name='TotalUtility',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
