# Generated by Django 3.2 on 2024-11-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEva3', '0005_warframe_totalutility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildresume',
            name='WarframeID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='Critical_Utility',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='Status_Utility',
            field=models.FloatField(),
        ),
    ]
